### ISSUE TITLE
[Rails 4.0] rake assets:precompile does not show any error/warning, but JS files are not grouped together in production

### ISSUE THREAD

**Issue by phanhaiquang** [jwhitley/requirejs-rails#137]
I added below line in Gemfile
gem 'requirejs-rails', git: 'git://github.com/jwhitley/requirejs-rails.git', branch: "master"   

"bundle install" does not have any issue.
"rake assets:precompile" does not show any issue, but there is no grouped js file in public/assets

Note: requirejs works fine in 'dev' environment. It means a .js could get dependant js file by define()
## Thanks much !

bundle exec rake assets:precompile --trace

*\* Invoke assets:precompile (first_time)
*\* Invoke assets:environment (first_time)
*\* Execute assets:environment
*\* Invoke environment (first_time)
*\* Execute environment
*\* Invoke requirejs:precompile:external (first_time)
*\* Invoke requirejs:test_node (first_time)
*\* Execute requirejs:test_node
*\* Execute requirejs:precompile:external
*\* Invoke requirejs:precompile:all (first_time)
*\* Invoke requirejs:precompile:prepare_source (first_time)
*\* Invoke requirejs:setup (first_time)
*\* Invoke assets:environment 
*\* Execute requirejs:setup

**Comment by paultyng** [comment]
I seem to be having the same issue as @lynndylanhurley still on the latest version.  My output file (single referenced module in the .yml) does not contain any dependencies but in the **/dst** folder the **almond.js** file gets all the built js.  If I don't use the almond loader, my build seems to work fine.
