### ISSUE TITLE
Custom modules break with sprockets-rails 2.2.0 (rails 4.1.6)

### ISSUE THREAD

**Issue by anselmbradford** [jwhitley/requirejs-rails#195]
In development with custom modules (see https://github.com/codeforamerica/ohana-web-search/blob/master/config/requirejs.yml#L13-L17), sprockets complains about the assets not being precompiled:

![screen shot 2014-10-13 at 5 02 30 pm](https://cloud.githubusercontent.com/assets/704760/4620087/4eb220e8-531c-11e4-961a-174bec39084b.png)

See https://github.com/codeforamerica/ohana-web-search/blob/master/config/environments/development.rb for development settings. I've tried adding `config.assets.digest = true` with no luck.

**Comment by csjohn** [comment]
Is @anselmbradford's last comment (Oct 13, 2014) correct? Is the README section about avoiding config assets precompile out of date?
