### ISSUE TITLE
Sprockets::Error: unknown compressor: js_compressor

### ISSUE THREAD

**Issue by fredericgrati** [jwhitley/requirejs-rails#201]
Hey guys,

when I try to build my assets with the following line : `bundle exec rake assets:precompile`

A error is raise :
`Sprockets::Error: unknown compressor: js_compressor`

in this [issue](https://github.com/jwhitley/requirejs-rails/issues/125#issuecomment-59229240), @jonesdhtx has the same problem than me but no response is given :/

ruby version: "2.1.3"
rails: "4.1.7"

Thx

**Comment by agis-** [comment]
@fredericgrati This was not your fault, it's requirejs-rails fault and maybe this is fixed by #206.
