### ISSUE TITLE
"Only one requirejs_include_tag allowed per page." false trigger

### ISSUE THREAD

**Issue by AdnanTheExcellent** [jwhitley/requirejs-rails#218]
I am encountering a very weird issue and I'm not sure why its happening. I have a development VM that uses ubuntu 14.04, ruby 2.0.0-p576, rails 4.0.0, and requirejs-rails 0.9.5. Heres is whats going on:

I can run the tests fine on my VM. everything passes. When i create a headless VM via vagrant (same versions as above), i keep getting the error "Only one requirejs_include_tag allowed per page." when i run my tests. I have exactly 1 instance of requirejs_include_tag in my code in my _header.html.erb file which i know is not rendered more than once per page.

I can run the server in development on both VMs no problem without getting the error. 

Any idea why this error is happening?

**Comment by carsomyr** [comment]
@AdnanTheExcellent Since this is all in some sort of stateless Rails controller, I'd suggest that you dump the backtrace of the `requirejs_include_tag`.

**Comment by carsomyr** [comment]
@AdnanTheExcellent Closing for now. Let me know if this is still occurring.
