### ISSUE TITLE
No such file or directory ending in "js.js"

### ISSUE THREAD

**Issue by qbraksa** [jwhitley/requirejs-rails#225]
Hi, 

A beginner issue probably, but when I try to do 

    bundle exec rake assets:precompile RAILS_ENV=production

Here's what I get : 

```
rake aborted!
Asset compilation with node failed with error:

{ [Error: Error: ENOENT, no such file or directory 
'/home/zak/TestLab/app/tmp/requirejs/dst/backbone/collections/unlisted_entries_collection.js.js'
```

Basically it's saying it didn't find `unlisted_entries_collection.js.js` which make sense since when I looked inside  `.../tmp/requirejs/dst/backbone/collections` I only found the `unlisted_entries_collection.js` and not 
`unlisted_entries_collection.js.js`

**Any ideas how can I fix this please ?**

Thanks!

**Comment by chenxeed** [comment]
Hmm, make sure that the file that you call in requirejs.yml is not called with extension ".js". Will it fix the issue?

**Comment by qbraksa** [comment]
Yep it did, that was exactly the issue! 

Thank you! +1
