### ISSUE TITLE
Asset precompilation fails with 0.9.6

### ISSUE THREAD

**Issue by declan** [jwhitley/requirejs-rails#226]
I've just locked the gem to 0.9.5 in my Gemfile, so this is not a pressing problem, but I thought I would post here in case others are having the same issue.

    $ rake assets:precompile --trace

    ** Invoke assets:precompile (first_time)
    ** Invoke assets:environment (first_time)
    ** Execute assets:environment
    ** Invoke environment (first_time)
    ** Execute environment
    ** Invoke requirejs:precompile:external (first_time)
    ** Invoke requirejs:test_node (first_time)
    ** Execute requirejs:test_node
    ** Execute requirejs:precompile:external
    /home/declan/.rvm/rubies/ruby-2.2.1/bin/ruby /home/declan/.rvm/rubies/ruby-2.2.1/bin/rake requirejs:precompile:all RAILS_ENV=production RAILS_GROUPS=assets --trace
    ** Invoke requirejs:precompile:all (first_time)
    ** Invoke requirejs:precompile:prepare_source (first_time)
    ** Invoke requirejs:setup (first_time)
    ** Invoke assets:environment (first_time)
    ** Execute assets:environment
    ** Invoke environment (first_time)
    ** Execute environment
    ** Execute requirejs:setup
    ** Invoke requirejs:clean (first_time)
    ** Invoke requirejs:setup 
    ** Execute requirejs:clean
    ** Execute requirejs:precompile:prepare_source
    rake aborted!
    NoMethodError: undefined method `[]' for nil:NilClass
    /home/declan/.rvm/gems/ruby-2.2.1@uihealth/gems/requirejs-rails-0.9.6/lib/tasks/requirejs-rails_tasks.rake:101:in `block (3 levels) in <top (required)>'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:199:in `each'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `each'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:75:in `run'
    /home/declan/.rvm/rubies/ruby-2.2.1/bin/rake:33:in `<main>'
    Tasks: TOP => requirejs:precompile:all => requirejs:precompile:prepare_source
    rake aborted!
    Command failed with status (1): [/home/declan/.rvm/rubies/ruby-2.2.1/bin/ru...]
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/file_utils.rb:66:in `block in create_shell_runner'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/file_utils.rb:57:in `call'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/file_utils.rb:57:in `sh'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/file_utils_ext.rb:37:in `sh'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/file_utils.rb:94:in `ruby'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/file_utils_ext.rb:37:in `ruby'
    /home/declan/.rvm/gems/ruby-2.2.1@uihealth/gems/requirejs-rails-0.9.6/lib/tasks/requirejs-rails_tasks.rake:18:in `ruby_rake_task'
    /home/declan/.rvm/gems/ruby-2.2.1@uihealth/gems/requirejs-rails-0.9.6/lib/tasks/requirejs-rails_tasks.rake:85:in `block (3 levels) in <top (required)>'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:199:in `each'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `each'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
    /home/declan/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:75:in `run'
    /home/declan/.rvm/rubies/ruby-2.2.1/bin/rake:33:in `<main>'
    Tasks: TOP => assets:precompile => requirejs:precompile:external

This is using Rails 4.2.1 on Ubuntu 14.04.

**Comment by carsomyr** [comment]
@declan Could you confirm that this is a dup of #221? If not, I'll reopen.
