### ISSUE TITLE
logical_asset_filter

### ISSUE THREAD

**Issue by merqlove** [jwhitley/requirejs-rails#229]
Seems that this implementation is wrong for now:
```
config.requirejs.logical_asset_filter += [/\.hamlbars/]
```

Unknown + method.

**Comment by merqlove** [comment]
Yes, seems that for it is: `logical_path_patterns`

**Comment by carsomyr** [comment]
@merqlove Sorry about that; didn't think that users would externally modify that value. Are you cool with using `logical_path_patterns`? What does the rest of the Rails codebase say about naming conventions?

**Comment by merqlove** [comment]
@carsomyr Yes, it works fine for me :+1: I use some custom template engines, like handlebars/hamlbars.
Speech above is about: logical_asset_filter unavailable from 2-3 latest releases ago. `logical_path_patterns` works fine => README :100:

**Comment by carsomyr** [comment]
@merqlove Alright, but if you can think of Rails naming conventions with regards to other, similar kinds of config values, let me know.
