### ISSUE TITLE
Assets not minified after upgrade to 0.9.3

### ISSUE THREAD

**Issue by agis-** [jwhitley/requirejs-rails#237]
Hello!

After upgrading from 0.9.1 to 0.9.3 on my Rails 3.2 app, I've noticed that assets are not minified anymore. I'm posting the snippet from a specific file, `application_desktop.js` (lines 1-40)

In 0.9.1 (expected output):
```javascript
define('vendor/modernizr_transitions',[], function() {
function b(e) {
s.cssText = e;
}
function w(e, t) {
return b(prefixes.join(e + ";") + (t || ""));
}
function E(e, t) {
return typeof e === t;
}
function S(e, t) {
return !!~("" + e).indexOf(t);
}
function x(e, t) {
for (var n in e) {
var r = e[n];
if (!S(r, "-") && s[r] !== undefined) return t == "pfx" ? r : !0;
}
return !1;
}
function T(e, t, n) {
for (var r in e) {
var i = t[e[r]];
if (i !== undefined) return n === !1 ? e[r] : E(i, "function") ? i.bind(n || t) : i;
}
return !1;
}
function N(e, t, n) {
var r = e.charAt(0).toUpperCase() + e.slice(1), i = (e + " " + f.join(r + " ") + r).split(" ");
return E(t, "string") || E(t, "undefined") ? x(i, t) : (i = (e + " " + l.join(r + " ") + r).split(" "), T(i, t, n));
}
var e = "2.6.1", t = {}, n = document.documentElement, r = "modernizr", i = document.createElement(r), s = i.style, o, u = {}.toString, a = "Webkit Moz O ms", f = a.split(" "), l = a.toLowerCase().split(" "), c = {}, h = {}, p = {}, d = [], v = d.slice, m, g = {}.hasOwnProperty, y;
!E(g, "undefined") && !E(g.call, "undefined") ? y = function(e, t) {
return g.call(e, t);
} : y = function(e, t) {
```

In 0.9.3 (incorrect output):

```javascript
define('vendor/modernizr_transitions',[],function(){

  var version = '2.6.1',

  Modernizr = {},


  docElement = document.documentElement,

  mod = 'modernizr',
  modElem = document.createElement(mod),
  mStyle = modElem.style,

  inputElem  ,


  toString = {}.toString,    omPrefixes = 'Webkit Moz O ms',

  cssomPrefixes = omPrefixes.split(' '),

  domPrefixes = omPrefixes.toLowerCase().split(' '),


  tests = {},
  inputs = {},
  attrs = {},

  classes = [],

  slice = classes.slice,

  featureName,



  _hasOwnProperty = ({}).hasOwnProperty, hasOwnProp;

  if ( !is(_hasOwnProperty, 'undefined') && !is(_hasOwnProperty.call, 'undefined') ) {
    hasOwnProp = function (object, property) {
      return _hasOwnProperty.call(object, property);
    };
  }
  else {
    hasOwnProp = function (object, property) {
      return ((property in object) && is(object.constructor.prototype[property], 'undefined'));
    };
  }
```

Any ideas?

**Comment by carsomyr** [comment]
@agis- Have you tried making the jump to `0.95`?

**Comment by agis-** [comment]
Sorry, forgot to mention that this happens in 0.9.5 and 0.9.8 too. It's just that 0.9.3 is the first "bad" version.

**Comment by carsomyr** [comment]
@agis- Is that a top-level module specified in `requirejs.yml`?

**Comment by agis-** [comment]
The setup is the one described in #236, so yes, it's a top-level module:

```yaml
# config/requirejs.yml

locale : 'en'
optimize : 'none'
paths:
  jquery.datepicker:  'vendor/jquery/plugins/jquery.datepicker'
  jquery.jcrop:       'vendor/jquery/plugins/jquery.jcrop'
modules :
  - name: 'application_desktop'

  - name: 'application_tablet'

  - name: 'application_mobile'

# ...
```

**Comment by agis-** [comment]
I've been thinking to try upgrading only requirejs in the working requirejs-rails version to 2.1.11 and see what happens. If the problem pops up, then it's an issue on the requirejs side.

**Comment by carsomyr** [comment]
Have you double checked your use of the optimizer?

**Comment by agis-** [comment]
I always had the r.js optimizer disabled (`optimize: 'none'` in *requirejs.yml*) in order to have the assets optimized with the global asset pipeline options that I use (Uglifier):

```ruby
  # config/environments/production.rb

  if defined? Uglifier
    config.assets.js_compressor = Uglifier.new(
      :mangle    => true,
      :toplevel  => false,
      :copyright => false,
      :beautify  => true,
      :beautify_options => {
        :indent_level => 0
      }
    )
  end
```

This setup was working fine with 0.9.0 and 0.9.1 but not with 0.9.3 apparently.

**Comment by agis-** [comment]
@carsomyr https://github.com/jwhitley/requirejs-rails/commit/fbc1e5c1f550d9a2be816e94f73626c53039c404 looks like a good suspect. It was introduced in 0.9.3.

What do you think?

**Comment by agis-** [comment]
I've confirmed that https://github.com/jwhitley/requirejs-rails/commit/fbc1e5c1f550d9a2be816e94f73626c53039c404 is the culprit. I've tried in 0.9.3 by commenting out that line and it works fine.

The thing is that by disabling the `js_compressor` so early in the initialization process, settings that were defined before it are overriden. I think this prevents certain setups like mine, which want to use a standalone compressor and not the one that comes with r.js, because when this is done in the initialization process, the settings remains throughout the life of the application.

This override wasn't happening prior to 0.9.3 that the compressor was disabled by a rake task, because the setting was persisted as long as the precompilation was running and not throughout the application process.

Not sure if I'm 100% correct though.

**Comment by agis-** [comment]
Hey @carsomyr, any feedback on this? It's really a blocker for upgrading to Rails 4.

**Comment by carsomyr** [comment]
@agis- Where does the compressor in your workflow come into play? Care to explain in depth?

**Comment by agis-** [comment]
Sure.

I'm on Rails 3.2.22 and requirejs-rails 0.9.0. The RequireJS optimizer is totally disabled:

```yaml
# config/requirejs.yml

optimize: 'none'
# ...
```

Instead, I have Uglifier set globally for the whole asset pipeline:

```ruby
# config/environments/production.rb

config.assets.js_compressor = Uglifier.new(
  :mangle    => true,
  :toplevel  => false,
  :copyright => false,
  :beautify  => true,
  :beautify_options => {
    :indent_level => 0
  }
)
```

The deploy flow is this:

1. `bundle exec rake assets:precompile` which in turn executes...
2.   `requirejs:precompile:all` and then
3.   `assets:precompile:all`

So the compression/minification of assets happens during step (3), once and for all the assets I have.

My assets are located in the usual locations and any RequireJS-specific files are located in `app/assets/javascripts/rjs/`.

This setup works fine in 0.9.0 that we are now, but breaks when upgrading to 0.9.3 in the ways I've explained in previous issues and because of https://github.com/jwhitley/requirejs-rails/commit/fbc1e5c1f550d9a2be816e94f73626c53039c404.

**Comment by agis-** [comment]
@carsomyr Hey, any insights? Thanks!

**Comment by carsomyr** [comment]
@agis- Hang in there. Looking to devote 3 consecutive nights this week to looking into requirejs-rails issues more deeply.

**Comment by agis-** [comment]
@carsomyr I'm grateful and willing to help any way I can. I'm currently upgrading from Rails 3.2.x to 4.0.x so I can provide insight while in the process of doing so.

**Comment by carsomyr** [comment]
@agis- Upgrading to Rails 4 may very well fix your issue. I'd recommend stripping down your app to the point where you can demonstrate the problem is occurring in Rails 4.

**Comment by agis-** [comment]
Upgrading requirejs-rails *after* upgrading to Rails 4.0 maybe sounds better. It's just that I was hoping to upgrade *before* so that the upgrade to Rails 4.0 is transparent as long as requirejs is concerned.

I have a long way for Rails 4 yet (maybe even a month), so it'll be a while before I get to the asset pipeline.

**Comment by carsomyr** [comment]
@agis- Here's your problem: A while back users were complaining that requirejs-rails was double-compressing their assets. One of the compressors had to give; in this case, it was the Rails compressor. If you'd like, you're welcome to file a pull request that:

1. Ignores the RequireJS compressor.
2. Uses whatever compressor Rails has registered to compress inlined modules.

I believe that this is a better solution because it's more Rails-y.

**Comment by agis-** [comment]
> One of the compressors had to give; in this case, it was the Rails compressor.

@carsomyr Can you point me to the relevant commit that changed the behavior? Was it https://github.com/jwhitley/requirejs-rails/commit/fbc1e5c1f550d9a2be816e94f73626c53039c404. It'd be great if we could have the *reasoning* behind this commit. Was it to disable the Rails compressor as you said?

**Comment by carsomyr** [comment]
@agis- Take a look at [this PR](https://github.com/jwhitley/requirejs-rails/pull/176). The reasoning for the commit 4ea9141 is to prevent double compression: Obfuscated assets should not be processed in a way that obfuscates them further. Also, RequireJS's purpose is to logically glue a bunch of JavaScripts together. Compressing JS before it even hits RequireJS's dependency solver is just bad. That's why I proposed ignoring the `r.js` compressor and instead using the asset pipeline's compressor after JavaScripts have been inlined.

**Comment by agis-** [comment]
@carsomyr Thanks for explaining. I'd be interested on preparing a PR that will switch to the asset pipeline compressor instead of the r.js compressor, but there are [certain issues](https://github.com/jwhitley/requirejs-rails/commit/c7babb62fe7418d23f7ae66c85a1519817c9b915) blocking me to do so.

This means I'm locked at 0.9.5 and cannot proceed to 0.9.6 cause of incompatibilities with Sprockers 2 (and I assume that will be more troubles on the way with 0.9.7 and later).

When I resolve these issues and upgrade to 0.9.9, I'd be able to work on this.
