### ISSUE TITLE
css files included with !text are getting stripped from /src/

### ISSUE THREAD

**Issue by lisunshiny** [jwhitley/requirejs-rails#272]
Hi,

I am currently trying to add the Ace editor library by adding this (https://github.com/ajaxorg/ace/tree/master/lib/ace) folder to `vendor/assets/javascripts/` in my Rails app and then calling `define(["ace/ace"], function(ace) {"blah"})` on to my project using the requirejs-rails gem. This is also in-line with the implementation instructions here: https://ace.c9.io/#nav=embedding.

Locally, this works fine. However, when I precompile assets for production, specifically on `bundle exec rake requirejs:precompile:run_rjs`, I'm getting the following error:
```
   { [Error: ENOENT: no such file or directory, open 'app/tmp/requirejs/dst/ace/css/editor.css']
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: 'app/tmp/requirejs/dst/ace/css/editor.css',
     moduleTree: 
      [ 'ace/requirejs/text',
        'ace/virtual_renderer',
        'ace/ace',
        'lib/ab-ace',
        'app/file-that-requires-ace' ],
     fileName: app/tmp/requirejs/dst/ace/requirejs/text.js' } }
```
Two things I noticed are:

* At first glance, in the `tmp/requirejs/dst/ace` file, the directory mirrors mine in `vendor/assets/javascripts/ace` but there are no `.css` files, just `.js` ones.
* The `require` statements that pull in css files use the `!text` header, such as here: https://github.com/ajaxorg/ace/blob/master/lib/ace/virtual_renderer.js#L47
* from #16, it seems like there is support for these `!text` files.

Really at a loss here for why these files aren't getting included -- any help would be greatly appreciated!

**Comment by lisunshiny** [comment]
Oh ok -- I figured this out. For other people trying to use the Ace editor and this gem, I added these regexes to the logical path patterns.

```
    config.requirejs.logical_path_patterns += [/\.jst.eco$/, /^ace\/[\w\/]*\w.+\.css$/, /\.snippets$/]
```

**Comment by carsomyr** [comment]
@lisunshiny Glad this feature worked out for you!
